[package]
name = "gamma-cli"
version = "0.2.0"
rust-version = "1.75.0"
edition = "2021"

[dependencies]
anchor-client = { workspace = true }
anchor-lang = { workspace = true }
anyhow = { workspace = true }
arrayref = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
clap = { workspace = true }
colorful = { workspace = true }
configparser = { workspace = true }
dotenv = { workspace = true }
gamma = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
solana-account = { workspace = true }
solana-client = { workspace = true }
solana-commitment-config = { workspace = true }
solana-keypair = { workspace = true }
solana-message = { workspace = true }
solana-program-pack = { workspace = true }
solana-pubkey = { workspace = true }
solana-account-decoder = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-system-interface = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
spl-token-interface = { workspace = true }
spl-memo-interface = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token-2022-interface = { workspace = true }
rust_decimal= {workspace=true}
jupiter-amm-interface = {workspace=true}
